repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: "docs/.*"
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md]
        exclude: "docs/.*"
      - id: check-json
        exclude: "docs/.*"
      - id: check-yaml
        args: [ --unsafe ]
        exclude: "docs/.*"
      - id: check-added-large-files
        exclude: "docs/.*"
      - id: check-ast
        exclude: "docs/.*"
  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.900
    hooks:
      - id: mypy
        pass_filenames: false
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
