name: Black Formatting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  runsLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install black isort
      - name: Check imports sort order
        run: python -m isort .
      - name: Check formatting style
        run: python -m black .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: ${{ github.head_ref }}
          commit-message: re-format code with black
          title: Black Formatting
          body: re-format code with black
          branch: black-format
          delete-branch: true
