name: Quality Checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  runsLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install flake8 mypy pydocstyle
      - name: Check formatting style
        run: python -m flake8 --count
      - name: Check type hints
        run: python -m mypy
      - name: Check documentation
        run: python -m pydocstyle
